### ISSUE TITLE
Installing using CLI get stuck

### ISSUE THREAD

**Issue by forkthat** [instantOS/instantOS#46]
On the warning that the drives will be erased, I tried to accept "yes" but doesn't come through.  I'm using Arch's 2020.08.01 ISO.

**Comment by paperbenni** [comment]
This should now be fixed
Let me know if it works now

**Comment by forkthat** [comment]
Man. that was fast!  Thank you.

**Comment by paperbenni** [comment]
So can I close this?

**Comment by forkthat** [comment]
Yes, you can.  If problems persist, I will just reply to this thread.  

Thanks, man.  You're so awesome.

**Comment by forkthat** [comment]
No problems installing in Virtualbox (I only tried to install here since I also encountered that same problem on VB some days ago and I still have to backup my files on the main OS before trying this on bare metal).  Thread now closing.
